backend/urls.py
from django.contrib import admin
from django.urls import path, include
# media upload
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('book.urls', 'book'), namespace='book')), # include( ('app.urls', 'app_name'), namespace='name' )
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/urls.py
from django.urls import path, re_path
# check premission to access path
from django.contrib.auth.decorators import login_required


from  . import views
urlpatterns = [
    path('', views.index, name="home"),
    path('book_detail/<slug:slug>', login_required(views.book_detail, login_url='book:login'), name='book-detail'),
    re_path(r'^book_add/$', login_required(views.book_add, login_url='book:login'), name='book-add'), # login before access path
    path('login', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup', views.signup_view, name = 'signup'),
]

book/models.py
from django.db import models
from django.utils.html import format_html
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories' # changed from 'Categorys' to 'Categories' (plural)

    def __str__(self):
        return self.name
    
class Author(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class LanguagesCoding(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
    
class Book(models.Model):
    BOOK_LEVEL_CHOICES = [
        ('B', 'Basic'),
        ('M', 'Medium'),
        ('A', 'Advance')
    ]

    code = models.IntegerField(blank=False, null=False)
    image = models.FileField(upload_to='upload/', null=1, blank=1)
    name = models.CharField(max_length=255, blank=False, null=False)
    slug = models.SlugField(max_length=255, blank=False, null=False)
    price = models.FloatField(default=0, null=False, blank=False)
    # Choice
    level = models.CharField('Level of Book', max_length=20, choices=BOOK_LEVEL_CHOICES, default=BOOK_LEVEL_CHOICES[0][1])
    # relationship
    languages = models.ForeignKey(LanguagesCoding, on_delete=models.CASCADE, null=True, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    author = models.ManyToManyField(Author, blank=True)
    
    published = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Book'
        ordering = ['-created']

    def show_image(self):
        if self.image:
            return format_html('<img src="{}" height="40px"'.format(self.image.url))
        return ''
    
    show_image.allow_tags = True
    show_image.short_description = 'Image Cover'

    def __str__(self):
        return self.name
    
class BookComment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rating = models.FloatField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=1)

    class Meta:
        ordering = ['-id']
        verbose_name_plural = 'Book Comment'

    def __str__(self):
        return self.comment
    

book/forms.py
from django.forms import ModelForm

from book.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        verbose_name = 'Book'
        verbose_name_plural = 'Books'
        exclude = ['code', 'slug', 'created', 'updated']

book/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
# import Paginator
from django.core.paginator import Paginator, InvalidPage, PageNotAnInteger, EmptyPage
# import Models
from .models import *
# import Forms
from .forms import *
#import python-slugify
from slugify import slugify
# import messages
from django.contrib import messages

# forms and login, logout
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

# Create your views here.
def index(request):
    book = Book.objects.all()
    categories = Category.objects.all()

    category_id = request.GET.get('category')
    if  category_id:
        book = Book.objects.filter(category=category_id)

    book_paginator = Paginator(book, 3)
    book_page = request.GET.get('page')
    try:
        book = book_paginator.page(book_page)
    except PageNotAnInteger:
        book = book_paginator.page(1)
    except EmptyPage:
        # if ?page over than number of pages, then set page = last page of pagination
        book = book_paginator.page(book_paginator.num_pages)
    except InvalidPage:
        book = book_paginator.page(1)

    return render(request, 'book/index.html', {'book':book, 'categories': categories, 'category_id':category_id})

def book_add(request):
    form = BookForm()

    if request.method == "POST":
        form = BookForm(request.POST, request.FILES) 
        if form.is_valid():
            book = form.save(commit=0) # insert data to form, but not commit 
            book.code = Book.objects.all().count() +1
            book.slug = slugify(book.name)
            book.save()
            form.save(commit=1)
            form.save_m2m()
            messages.success(request=request, message="Add New Book Success")
            return HttpResponseRedirect(reverse('book:home',kwargs={}))
        messages.error(request, 'Something went Wrongs !!')
        
    return render(request, 'book/book_add.html', {'form':form})

def book_detail(request, slug):
    book = Book.objects.get(slug=slug)
    return render(request, 'book/book_detail.html', {'slug':slug, 'book':book})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('book:home')
    else:
        form = AuthenticationForm()

    return render(request, 'account/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('book:home')

def signup_view(request):
    
    if request.method == 'POST': # click sign up form
        form = UserCreationForm(request.POST)
        if form.is_valid():
            newUser = form.save(commit=1)
            login(request, newUser)
            return redirect('book:home')
    else: # if visit by path()
        form = UserCreationForm()

    return render(request, 'book/signup.html', {'form':form})

templates/book/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="icon" href="{% static 'img/logo.ico' %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% include './nav.html' %}

    {% if messages %}
    <div class="container">
        {% for m in messages %}
            {% if m.tags == 'success' %} {# if messages tags status == 'success' #}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success {{ m }}</strong> You should check in on some of those fields below.
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% endif %}

    {% block content %}{% endblock content %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</body>
</html>

templates/book/book_add.html
{% extends './base.html' %}

{% load crispy_forms_tags %}

{% block title %}New Book{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-6 offset-3">
            <div class="display-4">New book</div>
            <hr>
            <form method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <table>{{ form|crispy }}</table>
                <button type="submit" class="btn btn-primary btn-block">Save</button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/book/book_detail.html
{% extends './base.html' %}

{% block title %}Detail{% endblock title %}

{% block content %}
    <div class="row w-100">
        <div class="col-6 offset-3">

            <div class="card">
                <div class="row mb-3">
                    <div class="col-4">
                        <img class="card-img-top img-fluid" src="{{ book.image.url }}">
                    </div>
                    <div class="col">
                        <div class="card-body">
                            <h4 class="card-title">{{ book.name }}</h4>
                            <p class="card-text">{{ book.price }}</p>
                            <p class="card-text">{{ book.description }}</p>
                            <p class="card-text">
                                <div class="text-muted"></div>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col"><a href="{% url 'book:home' %}" class="btn btn-info btn-block">Back</a></div>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

templates/book/index.html
{% extends './base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-3">
                <div class="card">
                    <h1 class="card-header mb-2">Category</h1>
                    <div class="list-group">
                        <a href="{% url 'book:home' %}" class="list-group-item list-group-item-action {% if not category_id %} active h5 {% endif %}">
                            All Book
                        </a>
                        {% for c in categories %}
                            <a href="{% url 'book:home' %}?category={{ c.id }}" class="list-group-item list-group-item-action {% if category_id|add:'0' == c.id %} active h5 {% endif %}">{{ c.name }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    {# book list #}
                    <h1 class="card-header">Book Store</h1>
                    <div class="row d-flex justify-content-start p-3">
                        {% for b in book %}
                        <div class="card m-1" style="width: 20rem;">
                            {% if b.image %}<img src="{{ b.image.url }}" class="card-img-top img-fluid" alt="book-cover">{% endif %}
                            <div class="card-body">
                                <h5 class="card-title"><strong>ชื่อหนังสือ : </strong>{{ b.name }}</h5>
                                <p class="card-text"><strong>ราคา : </strong>{{ b.price|floatformat:'2'}} บาท</p>
                                <p class="card-text">
                                    <strong>ผู้แต่ง : </strong>
                                    {% for author in b.author.all %}
                                        <span class="badge badge-secondary">{{ author.name }}</span>
                                    {% endfor %}
                                </p>
                                <p class="card-text">
                                    <strong>หมวดหมู่ : </strong>
                                    {% for c in b.category.all %}
                                        <span class="badge badge-warning text-white">{{ c.name }}</span>
                                    {% endfor %}
                                </p>
                                <a href="{% url 'book:book-detail' b.slug %}" class="btn btn-sm btn-info btn-block">Detail</a>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                {# pagination #}
                <nav class="d-flex justify-content-center">
                    <ul class="pagination">
                        {% if book.has_previous %}<li class="page-item"><a class="page-link" href="{% url 'book:home' %}?page={{ book.previous_page_number }}">Previous</a></li>{% endif %}
                        {% for i in book.paginator.page_range %}
                            <li class="page-item {% if book.number == i %}active{% endif %}">
                                <a class="page-link" href="{% url 'book:home' %}?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        {% if book.has_next %}<li class="page-item"><a class="page-link" href="{% url 'book:home' %}?page={{ book.next_page_number }}">Next</a></li>{% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock content %}

templates/book/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
    <a class="navbar-brand" href="{% url 'book:home' %}">
        <img src="{% static 'img/logo.ico' %}" alt="img-logo" class='img-fluid' style="width: 3rem;">
        Book
    </a>
    
    <ul class="navbar-nav ml-auto mx-4 px-2">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'book:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'book:book-add' %}">Add Book</a>
        </li>
        
        <li>
            {% if user.is_authenticated %}
                <span>{{ request.user.username }}</span>
                <form action="{% url 'book:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Logout</button>
                </form> 
            {% else %}
                <li class="nav-item mx-3">
                    <a class="nav-link btn btn-outline-success text-white" href="{% url 'book:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link btn btn-warning text-white" href="{% url 'book:signup' %}">Sign Up</a>
                </li>
            {% endif %} 

        </li>
    </ul>
</nav>

templates/book/signup.html
{% extends './base.html' %}

{% load crispy_forms_tags %}

{% block title %}Register{% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-4">
            <h1>img</h1>
        </div>
        <div class="col">
            <h1>form</h1>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Register & login</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}